name: CI for CT-AI Evaluation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute LIME notebook (Chapter 9)
        continue-on-error: true
        run: |
          echo "⚙️ Running 02_explainability_lime.ipynb..."
          jupyter nbconvert --to notebook --inplace --execute week04_explainability_ethics_review/notebooks/02_explainability_lime.ipynb \
          || echo "❌ LIME notebook failed, but continuing."

      - name: Execute Defect Prediction notebook
        continue-on-error: true
        run: |
          echo "⚙️ Running 03_defect_prediction.ipynb..."
          jupyter nbconvert --to notebook --inplace --execute week04_explainability_ethics_review/notebooks/03_defect_prediction.ipynb \
          || echo "❌ Defect Prediction notebook failed, but continuing."
